/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import AppPackage.AnimationClass;
import java.awt.Color;
import java.awt.Frame;
import java.awt.geom.RoundRectangle2D;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import main.Book;
import main.DatabaseQuery;
import main.SupportFunctions;

/**
 *
 * @author lampard
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form mainGUI
     */
    AnimationClass AC = new AnimationClass();
    ArrayList<JLabel> resultName = new ArrayList<>();
    ArrayList<JLabel> resultImage = new ArrayList<>();
    ArrayList<JPanel> resultPanel = new ArrayList<>();
    ResultSet res;
    int currentPage = 1;
    int maxPage = 1;
    int quantityPerPage = 10;
    int resultNum = 0;
    public HomePage() {
        this.setResizable(false);
        initComponents();
        this.setShape(new RoundRectangle2D.Float(0, 0, 1000, 600, 45, 45));
        this.setSize(1000, 600);
        resultName.add(ResultName1);
        resultName.add(ResultName2);
        resultName.add(ResultName3);
        resultName.add(ResultName4);
        resultName.add(ResultName5);
        resultName.add(ResultName6);
        resultName.add(ResultName7);
        resultName.add(ResultName8);
        resultName.add(ResultName9);
        resultName.add(ResultName10);
        resultImage.add(ResultImage1);
        resultImage.add(ResultImage2);
        resultImage.add(ResultImage3);
        resultImage.add(ResultImage4);
        resultImage.add(ResultImage5);
        resultImage.add(ResultImage6);
        resultImage.add(ResultImage7);
        resultImage.add(ResultImage8);
        resultImage.add(ResultImage9);
        resultImage.add(ResultImage10);
        resultPanel.add(Result1);
        resultPanel.add(Result2);
        resultPanel.add(Result3);
        resultPanel.add(Result4);
        resultPanel.add(Result5);
        resultPanel.add(Result6);
        resultPanel.add(Result7);
        resultPanel.add(Result8);
        resultPanel.add(Result9);
        resultPanel.add(Result10);
        pnShowResult.hide();
        res = DatabaseQuery.GetAllBook();
        resultNum = SupportFunctions.GetSize(res);
        lbResultNum.setText("Có " + String.valueOf(resultNum)+" kết quả.");
        lbCurrentPage.setText("Trang hiện tại: "+ String.valueOf(currentPage));
        maxPage = SupportFunctions.getMaxPage(resultNum, quantityPerPage);
        res = SupportFunctions.Display(resultImage, resultName, res, currentPage);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnMain = new javax.swing.JPanel();
        pnLeft = new javax.swing.JPanel();
        pnHome = new javax.swing.JPanel();
        lbHome = new javax.swing.JLabel();
        lbHome1 = new javax.swing.JLabel();
        pnHistory = new javax.swing.JPanel();
        lbHistory = new javax.swing.JLabel();
        lbUser1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        main = new javax.swing.JPanel();
        Result1 = new javax.swing.JPanel();
        ResultImage1 = new javax.swing.JLabel();
        Result6 = new javax.swing.JPanel();
        ResultImage6 = new javax.swing.JLabel();
        ResultName1 = new javax.swing.JLabel();
        Result2 = new javax.swing.JPanel();
        ResultImage2 = new javax.swing.JLabel();
        Result3 = new javax.swing.JPanel();
        ResultImage3 = new javax.swing.JLabel();
        Result4 = new javax.swing.JPanel();
        ResultImage4 = new javax.swing.JLabel();
        Result5 = new javax.swing.JPanel();
        ResultImage5 = new javax.swing.JLabel();
        Result7 = new javax.swing.JPanel();
        ResultImage7 = new javax.swing.JLabel();
        Result8 = new javax.swing.JPanel();
        ResultImage8 = new javax.swing.JLabel();
        Result9 = new javax.swing.JPanel();
        ResultImage9 = new javax.swing.JLabel();
        Result10 = new javax.swing.JPanel();
        ResultImage10 = new javax.swing.JLabel();
        ResultName2 = new javax.swing.JLabel();
        ResultName3 = new javax.swing.JLabel();
        ResultName4 = new javax.swing.JLabel();
        ResultName5 = new javax.swing.JLabel();
        ResultName6 = new javax.swing.JLabel();
        ResultName7 = new javax.swing.JLabel();
        ResultName8 = new javax.swing.JLabel();
        ResultName9 = new javax.swing.JLabel();
        ResultName10 = new javax.swing.JLabel();
        pnNext = new javax.swing.JPanel();
        lbNext = new javax.swing.JLabel();
        pnPrevious = new javax.swing.JPanel();
        lbPrevious = new javax.swing.JLabel();
        lbCurrentPage = new javax.swing.JLabel();
        lbResultNum = new javax.swing.JLabel();
        pnShowResult = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbResult = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taResult = new javax.swing.JTextArea();
        pnBack = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lbCancel = new javax.swing.JLabel();
        lbMinimize = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbMinimize1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(53, 53, 53));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnMain.setBackground(new java.awt.Color(255, 247, 238));
        pnMain.setAlignmentX(0.0F);
        pnMain.setAlignmentY(0.0F);
        pnMain.setDoubleBuffered(false);
        pnMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnLeft.setBackground(new java.awt.Color(38, 40, 55));
        pnLeft.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pnHome.setBackground(new java.awt.Color(38, 40, 55));

        lbHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/Home_32px_2.png"))); // NOI18N

        lbHome1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbHome1.setForeground(new java.awt.Color(255, 255, 255));
        lbHome1.setText("Trang Chủ");
        lbHome1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbHome1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbHome1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbHome1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbHome1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnHomeLayout = new javax.swing.GroupLayout(pnHome);
        pnHome.setLayout(pnHomeLayout);
        pnHomeLayout.setHorizontalGroup(
            pnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHomeLayout.createSequentialGroup()
                .addComponent(lbHome, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbHome1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnHomeLayout.setVerticalGroup(
            pnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbHome, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
            .addComponent(lbHome1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnHistory.setBackground(new java.awt.Color(38, 40, 55));

        lbHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/User_32px_1.png"))); // NOI18N

        lbUser1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lbUser1.setForeground(new java.awt.Color(255, 255, 255));
        lbUser1.setText("Đăng Nhập");
        lbUser1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbUser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbUser1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbUser1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbUser1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnHistoryLayout = new javax.swing.GroupLayout(pnHistory);
        pnHistory.setLayout(pnHistoryLayout);
        pnHistoryLayout.setHorizontalGroup(
            pnHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHistoryLayout.createSequentialGroup()
                .addComponent(lbHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbUser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnHistoryLayout.setVerticalGroup(
            pnHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbHistory, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
            .addComponent(lbUser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(38, 40, 55));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/Search_32px_1.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 7, 30, 30));

        searchField.setBackground(new java.awt.Color(38, 40, 55));
        searchField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        searchField.setForeground(new java.awt.Color(255, 255, 255));
        searchField.setBorder(null);
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });
        jPanel1.add(searchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 2, 140, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 32, 150, 10));

        javax.swing.GroupLayout pnLeftLayout = new javax.swing.GroupLayout(pnLeft);
        pnLeft.setLayout(pnLeftLayout);
        pnLeftLayout.setHorizontalGroup(
            pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnHistory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnLeftLayout.setVerticalGroup(
            pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLeftLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnHistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(335, Short.MAX_VALUE))
        );

        pnMain.add(pnLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        main.setBackground(new java.awt.Color(255, 247, 238));
        main.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Result1.setBackground(new java.awt.Color(255, 247, 238));
        Result1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ResultImage1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ResultImage1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ResultImage1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Result1.add(ResultImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 170));

        main.add(Result1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 11, -1, -1));

        Result6.setBackground(new java.awt.Color(255, 247, 238));
        Result6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ResultImage6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ResultImage6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Result6.add(ResultImage6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 170));

        main.add(Result6, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 223, -1, -1));

        ResultName1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ResultName1.setForeground(new java.awt.Color(0, 51, 204));
        ResultName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ResultName1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ResultName1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResultName1MouseClicked(evt);
            }
        });
        main.add(ResultName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 187, 130, 30));

        Result2.setBackground(new java.awt.Color(255, 247, 238));
        Result2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ResultImage2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ResultImage2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ResultImage2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Result2.add(ResultImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 170));

        main.add(Result2, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 11, -1, -1));

        Result3.setBackground(new java.awt.Color(255, 247, 238));
        Result3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ResultImage3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ResultImage3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ResultImage3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Result3.add(ResultImage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 170));

        main.add(Result3, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 11, -1, -1));

        Result4.setBackground(new java.awt.Color(255, 247, 238));
        Result4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ResultImage4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ResultImage4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Result4.add(ResultImage4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 170));

        main.add(Result4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 11, -1, -1));

        Result5.setBackground(new java.awt.Color(255, 247, 238));
        Result5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ResultImage5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ResultImage5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Result5.add(ResultImage5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 170));

        main.add(Result5, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 11, -1, -1));

        Result7.setBackground(new java.awt.Color(255, 247, 238));
        Result7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ResultImage7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ResultImage7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Result7.add(ResultImage7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 170));

        main.add(Result7, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 223, -1, -1));

        Result8.setBackground(new java.awt.Color(255, 247, 238));
        Result8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ResultImage8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ResultImage8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Result8.add(ResultImage8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 170));

        main.add(Result8, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 223, -1, -1));

        Result9.setBackground(new java.awt.Color(255, 247, 238));
        Result9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ResultImage9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ResultImage9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Result9.add(ResultImage9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 170));

        main.add(Result9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 223, -1, -1));

        Result10.setBackground(new java.awt.Color(255, 247, 238));
        Result10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ResultImage10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ResultImage10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Result10.add(ResultImage10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 170));

        main.add(Result10, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 223, -1, -1));

        ResultName2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ResultName2.setForeground(new java.awt.Color(0, 51, 204));
        ResultName2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ResultName2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ResultName2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResultName2MouseClicked(evt);
            }
        });
        main.add(ResultName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 187, 130, 30));

        ResultName3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ResultName3.setForeground(new java.awt.Color(0, 51, 204));
        ResultName3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ResultName3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ResultName3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResultName3MouseClicked(evt);
            }
        });
        main.add(ResultName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 187, 130, 30));

        ResultName4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ResultName4.setForeground(new java.awt.Color(0, 51, 204));
        ResultName4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ResultName4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ResultName4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResultName4MouseClicked(evt);
            }
        });
        main.add(ResultName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 187, 130, 30));

        ResultName5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ResultName5.setForeground(new java.awt.Color(0, 51, 204));
        ResultName5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ResultName5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ResultName5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResultName5MouseClicked(evt);
            }
        });
        main.add(ResultName5, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 187, 130, 30));

        ResultName6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ResultName6.setForeground(new java.awt.Color(0, 51, 204));
        ResultName6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ResultName6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ResultName6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResultName6MouseClicked(evt);
            }
        });
        main.add(ResultName6, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 399, 130, 30));

        ResultName7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ResultName7.setForeground(new java.awt.Color(0, 51, 204));
        ResultName7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ResultName7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ResultName7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResultName7MouseClicked(evt);
            }
        });
        main.add(ResultName7, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 399, 130, 30));

        ResultName8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ResultName8.setForeground(new java.awt.Color(0, 51, 204));
        ResultName8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ResultName8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ResultName8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResultName8MouseClicked(evt);
            }
        });
        main.add(ResultName8, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 399, 129, 30));

        ResultName9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ResultName9.setForeground(new java.awt.Color(0, 51, 204));
        ResultName9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ResultName9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ResultName9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResultName9MouseClicked(evt);
            }
        });
        main.add(ResultName9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 399, 130, 30));

        ResultName10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ResultName10.setForeground(new java.awt.Color(0, 51, 204));
        ResultName10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ResultName10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ResultName10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResultName10MouseClicked(evt);
            }
        });
        main.add(ResultName10, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 399, 130, 30));

        pnNext.setBackground(new java.awt.Color(38, 40, 55));

        lbNext.setBackground(new java.awt.Color(255, 255, 255));
        lbNext.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbNext.setForeground(new java.awt.Color(255, 255, 255));
        lbNext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNext.setText("Next");
        lbNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbNextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbNextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbNextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnNextLayout = new javax.swing.GroupLayout(pnNext);
        pnNext.setLayout(pnNextLayout);
        pnNextLayout.setHorizontalGroup(
            pnNextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbNext, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        pnNextLayout.setVerticalGroup(
            pnNextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbNext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        main.add(pnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 435, 70, 20));

        pnPrevious.setBackground(new java.awt.Color(38, 40, 55));

        lbPrevious.setBackground(new java.awt.Color(255, 255, 255));
        lbPrevious.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbPrevious.setForeground(new java.awt.Color(255, 255, 255));
        lbPrevious.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPrevious.setText("Previous");
        lbPrevious.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbPrevious.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPreviousMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbPreviousMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbPreviousMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnPreviousLayout = new javax.swing.GroupLayout(pnPrevious);
        pnPrevious.setLayout(pnPreviousLayout);
        pnPreviousLayout.setHorizontalGroup(
            pnPreviousLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbPrevious, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        pnPreviousLayout.setVerticalGroup(
            pnPreviousLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbPrevious, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        main.add(pnPrevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 435, 70, 20));

        lbCurrentPage.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lbCurrentPage.setText("Trang hiện tại: ");
        main.add(lbCurrentPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 435, 120, 20));

        lbResultNum.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lbResultNum.setText("Có: kết quả");
        main.add(lbResultNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 435, 120, 20));

        pnMain.add(main, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 830, 540));

        pnShowResult.setBackground(new java.awt.Color(255, 247, 238));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(lbResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 350));

        taResult.setEditable(false);
        taResult.setBackground(new java.awt.Color(38, 40, 55));
        taResult.setColumns(20);
        taResult.setFont(new java.awt.Font("Monospaced", 1, 20)); // NOI18N
        taResult.setForeground(new java.awt.Color(255, 255, 255));
        taResult.setRows(5);
        taResult.setTabSize(4);
        taResult.setWrapStyleWord(true);
        jScrollPane1.setViewportView(taResult);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 0, 500, 350));

        pnBack.setBackground(new java.awt.Color(38, 40, 55));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Back");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnBackLayout = new javax.swing.GroupLayout(pnBack);
        pnBack.setLayout(pnBackLayout);
        pnBackLayout.setHorizontalGroup(
            pnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnBackLayout.setVerticalGroup(
            pnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnShowResultLayout = new javax.swing.GroupLayout(pnShowResult);
        pnShowResult.setLayout(pnShowResultLayout);
        pnShowResultLayout.setHorizontalGroup(
            pnShowResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnShowResultLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnShowResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        pnShowResultLayout.setVerticalGroup(
            pnShowResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnShowResultLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(pnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnMain.add(pnShowResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 850, 460));

        getContentPane().add(pnMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1010, 460));

        jPanel4.setBackground(new java.awt.Color(53, 53, 53));
        jPanel4.setPreferredSize(new java.awt.Dimension(1000, 43));

        lbCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/Cancel_32px.png"))); // NOI18N
        lbCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbCancelMouseClicked(evt);
            }
        });

        lbMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/Minimize Window_32px_2.png"))); // NOI18N
        lbMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMinimizeMouseClicked(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Thư Viện Đại Học Bách Khoa");

        lbMinimize1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/bkLogo3.png"))); // NOI18N
        lbMinimize1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbMinimize1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 334, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(304, 304, 304)
                .addComponent(lbMinimize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbCancel)
                .addGap(21, 21, 21))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(lbMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbMinimize1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/banner2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1010, 110));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void setText(JTextArea taResult, Book book) {
        taResult.setText("\n\n");
        taResult.append("  Tên: \t\t\t\t" + book.getName() + "\n");
        taResult.append("  SKU: \t\t\t\t" + book.getSKU() + "\n");
        taResult.append("  Tác giả: \t\t\t" + book.getAuthor() + "\n");
        taResult.append("  Nhà xuất bản: \t" + book.getPublisher() + "\n");
        taResult.append("  Ngày xuất bản: \t" + book.getPublishedDay() + "\n");
        taResult.append("  Thể loại: \t\t" + book.getGendre() + "\n");
    }

    public void setResult(JTextArea taResult, JLabel lbResult, Book book) {
        setText(taResult, book);
        String URL;
        if (SupportFunctions.checkBookImageExist(book.getSKU())) {
            URL = "Images/Books/" + book.getSKU() + ".jpg";
        } else {
            URL = "Images/NoPhotoAvailable.jpg";
        }
        SupportFunctions.setImageToLabel(lbResult, URL);
    }

    public void setClick(int i) {
        if (!resultName.get(i - 1).getText().equals(null)) {
            main.hide();
            pnShowResult.show();
            setResult(taResult, lbResult, DatabaseQuery.findBookByExactName(resultName.get(i - 1).getText()));
        }
    }

    private void lbCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCancelMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lbCancelMouseClicked

    private void lbMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMinimizeMouseClicked
        // TODO add your handling code here:
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_lbMinimizeMouseClicked

    private void lbHome1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbHome1MouseExited
        // TODO add your handling code here:
        pnHome.setBackground(new Color(38, 40, 55));
    }//GEN-LAST:event_lbHome1MouseExited

    private void lbHome1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbHome1MouseEntered
        // TODO add your handling code here:
        pnHome.setBackground(new Color(0, 116, 163));
    }//GEN-LAST:event_lbHome1MouseEntered

    private void lbUser1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbUser1MouseExited
        // TODO add your handling code here:
        pnHistory.setBackground(new Color(38, 40, 55));
    }//GEN-LAST:event_lbUser1MouseExited

    private void lbUser1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbUser1MouseEntered
        // TODO add your handling code here:
        pnHistory.setBackground(new Color(0, 116, 163));
    }//GEN-LAST:event_lbUser1MouseEntered

    private void lbUser1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbUser1MouseClicked
        // TODO add your handling code here:

        new LoginSite().setVisible(true);
    }//GEN-LAST:event_lbUser1MouseClicked

    private void lbNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNextMouseClicked
        // TODO add your handling code here:
        if (currentPage < maxPage) {
            currentPage++;
            lbCurrentPage.setText("Trang hiện tại: "+ String.valueOf(currentPage));
            res = SupportFunctions.Display(resultImage, resultName, res, currentPage);
        }
    }//GEN-LAST:event_lbNextMouseClicked

    private void lbPreviousMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPreviousMouseClicked
        // TODO add your handling code here:
        if (currentPage > 1) {
            currentPage--;
            lbCurrentPage.setText("Trang hiện tại: "+ String.valueOf(currentPage));
            res = SupportFunctions.Display(resultImage, resultName, res, currentPage);
        }
    }//GEN-LAST:event_lbPreviousMouseClicked

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
        main.show();
        res = DatabaseQuery.SearchBookByKeyWord(searchField.getText());
        resultNum = SupportFunctions.GetSize(res);
        lbResultNum.setText("Có " + String.valueOf(resultNum)+" kết quả.");
        maxPage = SupportFunctions.getMaxPage(resultNum, quantityPerPage);
        res = SupportFunctions.Display(resultImage, resultName, res, currentPage = 1);
        lbCurrentPage.setText("Trang hiện tại: "+ String.valueOf(currentPage));
    }//GEN-LAST:event_searchFieldActionPerformed

    private void lbPreviousMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPreviousMouseEntered
        // TODO add your handling code here:
        if (currentPage > 1) {
            Admin.changeBackPanelEntered(pnPrevious);
        }
    }//GEN-LAST:event_lbPreviousMouseEntered

    private void lbPreviousMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPreviousMouseExited
        // TODO add your handling code here:
        Admin.changeBackPanelExited(pnPrevious);
    }//GEN-LAST:event_lbPreviousMouseExited

    private void lbNextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNextMouseEntered
        // TODO add your handling code here:
        if (currentPage < maxPage) {
            Admin.changeBackPanelEntered(pnNext);
        }
    }//GEN-LAST:event_lbNextMouseEntered

    private void lbNextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNextMouseExited
        // TODO add your handling code here:
        Admin.changeBackPanelExited(pnNext);
    }//GEN-LAST:event_lbNextMouseExited

    private void ResultName1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResultName1MouseClicked
        // TODO add your handling code here:
        setClick(1);
    }//GEN-LAST:event_ResultName1MouseClicked

    private void ResultName2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResultName2MouseClicked
        // TODO add your handling code here:
        setClick(2);
    }//GEN-LAST:event_ResultName2MouseClicked

    private void ResultName3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResultName3MouseClicked
        // TODO add your handling code here:
        setClick(3);
    }//GEN-LAST:event_ResultName3MouseClicked

    private void ResultName4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResultName4MouseClicked
        // TODO add your handling code here:
        setClick(4);
    }//GEN-LAST:event_ResultName4MouseClicked

    private void ResultName5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResultName5MouseClicked
        // TODO add your handling code here:
        setClick(5);
    }//GEN-LAST:event_ResultName5MouseClicked

    private void ResultName6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResultName6MouseClicked
        // TODO add your handling code here:
        setClick(6);
    }//GEN-LAST:event_ResultName6MouseClicked

    private void ResultName7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResultName7MouseClicked
        // TODO add your handling code here:
        setClick(7);
    }//GEN-LAST:event_ResultName7MouseClicked

    private void ResultName8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResultName8MouseClicked
        // TODO add your handling code here:
        setClick(8);
    }//GEN-LAST:event_ResultName8MouseClicked

    private void ResultName9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResultName9MouseClicked
        // TODO add your handling code here:
        setClick(9);
    }//GEN-LAST:event_ResultName9MouseClicked

    private void ResultName10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResultName10MouseClicked
        // TODO add your handling code here:
        setClick(10);
    }//GEN-LAST:event_ResultName10MouseClicked

    private void lbHome1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbHome1MouseClicked
        // TODO add your handling code here:
        main.show();
        pnShowResult.hide();
        searchField.setText(null);
        res = DatabaseQuery.GetAllBook();
        resultNum = SupportFunctions.GetSize(res);
        lbResultNum.setText("Có " + String.valueOf(resultNum)+" kết quả.");
        maxPage = SupportFunctions.getMaxPage(resultNum, quantityPerPage);
        res = SupportFunctions.Display(resultImage, resultName, res, currentPage = 1);
        lbCurrentPage.setText("Trang hiện tại: "+ String.valueOf(currentPage));
    }//GEN-LAST:event_lbHome1MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
         main.show();
        pnShowResult.hide();
        res = SupportFunctions.Display(resultImage, resultName, res, currentPage);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        // TODO add your handling code here:
        pnBack.setBackground(new Color(0, 116, 163));
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        // TODO add your handling code here:
        pnBack.setBackground(new Color(38, 40, 55));
    }//GEN-LAST:event_jLabel4MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Result1;
    private javax.swing.JPanel Result10;
    private javax.swing.JPanel Result2;
    private javax.swing.JPanel Result3;
    private javax.swing.JPanel Result4;
    private javax.swing.JPanel Result5;
    private javax.swing.JPanel Result6;
    private javax.swing.JPanel Result7;
    private javax.swing.JPanel Result8;
    private javax.swing.JPanel Result9;
    private javax.swing.JLabel ResultImage1;
    private javax.swing.JLabel ResultImage10;
    private javax.swing.JLabel ResultImage2;
    private javax.swing.JLabel ResultImage3;
    private javax.swing.JLabel ResultImage4;
    private javax.swing.JLabel ResultImage5;
    private javax.swing.JLabel ResultImage6;
    private javax.swing.JLabel ResultImage7;
    private javax.swing.JLabel ResultImage8;
    private javax.swing.JLabel ResultImage9;
    private javax.swing.JLabel ResultName1;
    private javax.swing.JLabel ResultName10;
    private javax.swing.JLabel ResultName2;
    private javax.swing.JLabel ResultName3;
    private javax.swing.JLabel ResultName4;
    private javax.swing.JLabel ResultName5;
    private javax.swing.JLabel ResultName6;
    private javax.swing.JLabel ResultName7;
    private javax.swing.JLabel ResultName8;
    private javax.swing.JLabel ResultName9;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbCancel;
    private javax.swing.JLabel lbCurrentPage;
    private javax.swing.JLabel lbHistory;
    private javax.swing.JLabel lbHome;
    private javax.swing.JLabel lbHome1;
    private javax.swing.JLabel lbMinimize;
    private javax.swing.JLabel lbMinimize1;
    private javax.swing.JLabel lbNext;
    private javax.swing.JLabel lbPrevious;
    private javax.swing.JLabel lbResult;
    private javax.swing.JLabel lbResultNum;
    private javax.swing.JLabel lbUser1;
    private javax.swing.JPanel main;
    private javax.swing.JPanel pnBack;
    private javax.swing.JPanel pnHistory;
    private javax.swing.JPanel pnHome;
    private javax.swing.JPanel pnLeft;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnNext;
    private javax.swing.JPanel pnPrevious;
    private javax.swing.JPanel pnShowResult;
    private javax.swing.JTextField searchField;
    private javax.swing.JTextArea taResult;
    // End of variables declaration//GEN-END:variables
}
