/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import AppPackage.AnimationClass;
import java.awt.Color;
import java.awt.Frame;
import java.awt.geom.RoundRectangle2D;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import main.Book;
import main.DatabaseQuery;
import main.SupportFunctions;
import javax.swing.JCheckBox;

/**
 *
 * @author lampard
 */
public class ReaderMain extends javax.swing.JFrame {
    String userName;
    ResultSet res;
    int currentPage = 1;
    int maxPage = 1;
    int quantityPerPage = 10;
    int resultNum = 0;
    
    AnimationClass AC = new AnimationClass();
    ArrayList<JLabel> resultName = new ArrayList<>();
    ArrayList<JLabel> resultImage = new ArrayList<>();
    ArrayList<JPanel> resultPanel = new ArrayList<>();
    /**
     * Creates new form mainGUI
     */
    public ReaderMain() {
        this.setResizable(false);
        initComponents();
        this.setShape(new RoundRectangle2D.Float(0, 0, 1000, 600, 45, 45));
        this.setSize(1000, 600);
        userName = "NGUYỄN VĂN THÀNH";
        
        resultName.add(lbResTxt1);
        resultName.add(lbResTxt2);
        resultName.add(lbResTxt3);
        resultName.add(lbResTxt4);
        resultName.add(lbResTxt5);
        resultName.add(lbResTxt6);
        resultName.add(lbResTxt7);
        resultName.add(lbResTxt8);
        resultName.add(lbResTxt9);
        resultName.add(lbResTxt10);
        resultImage.add(lbResImg1);
        resultImage.add(lbResImg2);
        resultImage.add(lbResImg3);
        resultImage.add(lbResImg4);
        resultImage.add(lbResImg5);
        resultImage.add(lbResImg6);
        resultImage.add(lbResImg7);
        resultImage.add(lbResImg8);
        resultImage.add(lbResImg9);
        resultImage.add(lbResImg10);
//        resultPanel.add(Result1);
//        resultPanel.add(Result2);
//        resultPanel.add(Result3);
//        resultPanel.add(Result4);
//        resultPanel.add(Result5);
//        resultPanel.add(Result6);
//        resultPanel.add(Result7);
//        resultPanel.add(Result8);
//        resultPanel.add(Result9);
//        resultPanel.add(Result10);
//        pnShowResult.hide();
        
    }
    
    
    public void changeBackPanel(int inpState){
        switch (inpState){
            case 2:
                pnReaderSearch.hide();
                pnReaderInfo.hide();
                pnReaderHistory.show();
                pnHistory.setBackground(new Color(0, 116, 163));
                pnHistory.disable();
                break;
            case 1:
                pnReaderHistory.hide();
                pnReaderInfo.hide();
                pnReaderSearch.show();
                pnSearch.setBackground(new Color(0, 116, 163));
                pnSearch.disable();
                break;
            case 3:
                pnReaderHistory.hide();
                pnReaderSearch.hide();
                pnReaderInfo.show();
            default:
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnMain = new javax.swing.JPanel();
        pnLeft = new javax.swing.JPanel();
        pnHome = new javax.swing.JPanel();
        lbHome = new javax.swing.JLabel();
        lbHome1 = new javax.swing.JLabel();
        pnHistory = new javax.swing.JPanel();
        lbHistory = new javax.swing.JLabel();
        lbHistory1 = new javax.swing.JLabel();
        pnUser = new javax.swing.JPanel();
        lbUserInfor = new javax.swing.JLabel();
        lbUserInfor1 = new javax.swing.JLabel();
        pnSearch = new javax.swing.JPanel();
        lbSearch = new javax.swing.JLabel();
        lbSearch1 = new javax.swing.JLabel();
        pnReaderSearch = new javax.swing.JPanel();
        pbMainSearch = new javax.swing.JPanel();
        lbSearch100 = new javax.swing.JLabel();
        tfSearch = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        cbName = new javax.swing.JCheckBox();
        cbAuthor = new javax.swing.JCheckBox();
        cbGenre = new javax.swing.JCheckBox();
        cbPublisher = new javax.swing.JCheckBox();
        cbID = new javax.swing.JCheckBox();
        cbISBN = new javax.swing.JCheckBox();
        lbResImg7 = new javax.swing.JLabel();
        lbResTxt2 = new javax.swing.JLabel();
        lbResImg6 = new javax.swing.JLabel();
        lbResImg8 = new javax.swing.JLabel();
        lbResImg9 = new javax.swing.JLabel();
        lbResImg10 = new javax.swing.JLabel();
        lbResTxt1 = new javax.swing.JLabel();
        lbResTxt4 = new javax.swing.JLabel();
        lbResTxt5 = new javax.swing.JLabel();
        lbResTxt3 = new javax.swing.JLabel();
        lbResTxt6 = new javax.swing.JLabel();
        lbResTxt7 = new javax.swing.JLabel();
        lbResTxt8 = new javax.swing.JLabel();
        lbResTxt9 = new javax.swing.JLabel();
        lbResTxt10 = new javax.swing.JLabel();
        lbResImg1 = new javax.swing.JLabel();
        lbResImg2 = new javax.swing.JLabel();
        lbResImg3 = new javax.swing.JLabel();
        lbResImg4 = new javax.swing.JLabel();
        lbResImg5 = new javax.swing.JLabel();
        lbResInfo = new javax.swing.JLabel();
        lbPrevious = new javax.swing.JLabel();
        lbNext = new javax.swing.JLabel();
        lbCurrent = new javax.swing.JLabel();
        pnReaderHistory = new javax.swing.JPanel();
        lbResImg11 = new javax.swing.JLabel();
        lbResImg12 = new javax.swing.JLabel();
        lbResImg13 = new javax.swing.JLabel();
        lbResImg14 = new javax.swing.JLabel();
        lbResImg15 = new javax.swing.JLabel();
        lbResTxt16 = new javax.swing.JLabel();
        lbResTxt17 = new javax.swing.JLabel();
        lbResTxt18 = new javax.swing.JLabel();
        lbResTxt19 = new javax.swing.JLabel();
        lbResTxt20 = new javax.swing.JLabel();
        pnReaderHistoryInfo = new javax.swing.JPanel();
        lbHInfo1 = new javax.swing.JLabel();
        lbHInfo3 = new javax.swing.JLabel();
        lbHInfo2 = new javax.swing.JLabel();
        lbHInfo4 = new javax.swing.JLabel();
        pnReaderInfo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pnAvatar = new javax.swing.JPanel();
        lbAvatar = new javax.swing.JLabel();
        lbBrowser = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lbCancel = new javax.swing.JLabel();
        lbMinimize = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbMinimize1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(53, 53, 53));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnMain.setBackground(new java.awt.Color(255, 247, 238));
        pnMain.setAlignmentX(0.0F);
        pnMain.setAlignmentY(0.0F);
        pnMain.setDoubleBuffered(false);
        pnMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnLeft.setBackground(new java.awt.Color(38, 40, 55));

        pnHome.setBackground(new java.awt.Color(38, 40, 55));

        lbHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/Home_32px_2.png"))); // NOI18N

        lbHome1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbHome1.setForeground(new java.awt.Color(255, 255, 255));
        lbHome1.setText("Trang Chủ");
        lbHome1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbHome1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbHome1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbHome1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbHome1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnHomeLayout = new javax.swing.GroupLayout(pnHome);
        pnHome.setLayout(pnHomeLayout);
        pnHomeLayout.setHorizontalGroup(
            pnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHomeLayout.createSequentialGroup()
                .addComponent(lbHome, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbHome1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnHomeLayout.setVerticalGroup(
            pnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbHome, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
            .addComponent(lbHome1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnHistory.setBackground(new java.awt.Color(38, 40, 55));

        lbHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/Historical_32px.png"))); // NOI18N

        lbHistory1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lbHistory1.setForeground(new java.awt.Color(255, 255, 255));
        lbHistory1.setText("Lịch Sử Mượn Sách");
        lbHistory1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbHistory1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbHistory1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbHistory1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbHistory1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnHistoryLayout = new javax.swing.GroupLayout(pnHistory);
        pnHistory.setLayout(pnHistoryLayout);
        pnHistoryLayout.setHorizontalGroup(
            pnHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHistoryLayout.createSequentialGroup()
                .addComponent(lbHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbHistory1, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
        );
        pnHistoryLayout.setVerticalGroup(
            pnHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbHistory, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
            .addComponent(lbHistory1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnUser.setBackground(new java.awt.Color(38, 40, 55));

        lbUserInfor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/User_32px_1.png"))); // NOI18N

        lbUserInfor1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lbUserInfor1.setForeground(new java.awt.Color(255, 255, 255));
        lbUserInfor1.setText("Thông Tin Cá Nhân");
        lbUserInfor1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbUserInfor1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbUserInfor1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbUserInfor1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbUserInfor1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnUserLayout = new javax.swing.GroupLayout(pnUser);
        pnUser.setLayout(pnUserLayout);
        pnUserLayout.setHorizontalGroup(
            pnUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnUserLayout.createSequentialGroup()
                .addComponent(lbUserInfor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbUserInfor1, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
        );
        pnUserLayout.setVerticalGroup(
            pnUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbUserInfor, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
            .addComponent(lbUserInfor1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnSearch.setBackground(new java.awt.Color(38, 40, 55));

        lbSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/Search_32px_1.png"))); // NOI18N

        lbSearch1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbSearch1.setForeground(new java.awt.Color(255, 255, 255));
        lbSearch1.setText("Tìm Kiếm");
        lbSearch1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbSearch1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbSearch1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbSearch1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbSearch1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnSearchLayout = new javax.swing.GroupLayout(pnSearch);
        pnSearch.setLayout(pnSearchLayout);
        pnSearchLayout.setHorizontalGroup(
            pnSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSearchLayout.createSequentialGroup()
                .addComponent(lbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbSearch1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnSearchLayout.setVerticalGroup(
            pnSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
            .addComponent(lbSearch1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnLeftLayout = new javax.swing.GroupLayout(pnLeft);
        pnLeft.setLayout(pnLeftLayout);
        pnLeftLayout.setHorizontalGroup(
            pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnHistory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnLeftLayout.setVerticalGroup(
            pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnHistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(377, Short.MAX_VALUE))
        );

        pnMain.add(pnLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 550));

        pnReaderSearch.setBackground(new java.awt.Color(255, 255, 255));
        pnReaderSearch.setPreferredSize(new java.awt.Dimension(820, 480));

        pbMainSearch.setBackground(new java.awt.Color(38, 40, 55));
        pbMainSearch.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbSearch100.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/Search_32px_1.png"))); // NOI18N
        pbMainSearch.add(lbSearch100, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 37));

        tfSearch.setBackground(new java.awt.Color(38, 40, 55));
        tfSearch.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        tfSearch.setForeground(new java.awt.Color(255, 255, 255));
        tfSearch.setBorder(null);
        tfSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSearchActionPerformed(evt);
            }
        });
        pbMainSearch.add(tfSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 200, 30));

        jSeparator1.setAlignmentX(0.0F);
        jSeparator1.setAlignmentY(0.0F);
        jSeparator1.setRequestFocusEnabled(false);
        pbMainSearch.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 200, 5));

        cbName.setBackground(new java.awt.Color(38, 40, 55));
        cbName.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cbName.setForeground(new java.awt.Color(255, 255, 255));
        cbName.setText("Tên Sách");
        cbName.setAlignmentY(0.0F);
        cbName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbNameMouseClicked(evt);
            }
        });
        cbName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNameActionPerformed(evt);
            }
        });
        pbMainSearch.add(cbName, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 7, -1, -1));

        cbAuthor.setBackground(new java.awt.Color(38, 40, 55));
        cbAuthor.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cbAuthor.setForeground(new java.awt.Color(255, 255, 255));
        cbAuthor.setText("Tác Giả");
        cbAuthor.setAlignmentY(0.0F);
        cbAuthor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbAuthorMouseClicked(evt);
            }
        });
        cbAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAuthorActionPerformed(evt);
            }
        });
        pbMainSearch.add(cbAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 7, -1, -1));

        cbGenre.setBackground(new java.awt.Color(38, 40, 55));
        cbGenre.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cbGenre.setForeground(new java.awt.Color(255, 255, 255));
        cbGenre.setText("Thể Loại");
        cbGenre.setAlignmentY(0.0F);
        cbGenre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbGenreMouseClicked(evt);
            }
        });
        pbMainSearch.add(cbGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 7, -1, -1));

        cbPublisher.setBackground(new java.awt.Color(38, 40, 55));
        cbPublisher.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cbPublisher.setForeground(new java.awt.Color(255, 255, 255));
        cbPublisher.setText("Nhà Xuất Bản");
        cbPublisher.setAlignmentY(0.0F);
        cbPublisher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbPublisherMouseClicked(evt);
            }
        });
        pbMainSearch.add(cbPublisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 7, -1, -1));

        cbID.setBackground(new java.awt.Color(38, 40, 55));
        cbID.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cbID.setForeground(new java.awt.Color(255, 255, 255));
        cbID.setText("Nhà Xuất Bản");
        cbID.setAlignmentY(0.0F);
        cbID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbIDMouseClicked(evt);
            }
        });
        pbMainSearch.add(cbID, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 7, -1, -1));

        cbISBN.setBackground(new java.awt.Color(38, 40, 55));
        cbISBN.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cbISBN.setForeground(new java.awt.Color(255, 255, 255));
        cbISBN.setAlignmentY(0.0F);
        cbISBN.setLabel("SKU");
        cbISBN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbISBNMouseClicked(evt);
            }
        });
        pbMainSearch.add(cbISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 70, 35));

        lbResImg7.setBackground(new java.awt.Color(100, 240, 150));

        lbResImg6.setBackground(new java.awt.Color(100, 240, 150));

        lbResImg8.setBackground(new java.awt.Color(100, 240, 150));

        lbResImg9.setBackground(new java.awt.Color(100, 240, 150));
        lbResImg9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lbResImg10.setBackground(new java.awt.Color(100, 240, 150));
        lbResImg10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lbResImg1.setBackground(new java.awt.Color(100, 240, 150));

        lbResImg2.setBackground(new java.awt.Color(100, 240, 150));

        lbResImg3.setBackground(new java.awt.Color(100, 240, 150));

        lbResImg4.setBackground(new java.awt.Color(100, 240, 150));
        lbResImg4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lbResImg5.setBackground(new java.awt.Color(100, 240, 150));
        lbResImg5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lbResInfo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbResInfo.setForeground(new java.awt.Color(0, 0, 102));
        lbResInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbResInfo.setText("Có tất cả ... kết quả");

        lbPrevious.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbPrevious.setForeground(new java.awt.Color(0, 0, 102));
        lbPrevious.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPrevious.setText("Previous");

        lbNext.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbNext.setForeground(new java.awt.Color(0, 0, 102));
        lbNext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNext.setText("Next");

        lbCurrent.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbCurrent.setText("Trang hiện tại: ");

        javax.swing.GroupLayout pnReaderSearchLayout = new javax.swing.GroupLayout(pnReaderSearch);
        pnReaderSearch.setLayout(pnReaderSearchLayout);
        pnReaderSearchLayout.setHorizontalGroup(
            pnReaderSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnReaderSearchLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnReaderSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnReaderSearchLayout.createSequentialGroup()
                        .addComponent(lbResTxt6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lbResTxt7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lbResTxt8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lbResTxt9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbResTxt10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnReaderSearchLayout.createSequentialGroup()
                        .addComponent(lbResInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(181, 181, 181)
                        .addComponent(lbCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbNext, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))
                    .addGroup(pnReaderSearchLayout.createSequentialGroup()
                        .addGroup(pnReaderSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbResImg6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbResTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbResImg1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnReaderSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnReaderSearchLayout.createSequentialGroup()
                                .addComponent(lbResImg2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(lbResImg3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnReaderSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pnReaderSearchLayout.createSequentialGroup()
                                    .addComponent(lbResTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(lbResTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnReaderSearchLayout.createSequentialGroup()
                                    .addComponent(lbResImg7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(lbResImg8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(30, 30, 30)
                        .addGroup(pnReaderSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbResImg9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbResTxt4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbResImg4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(pnReaderSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbResImg10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbResTxt5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbResImg5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32))
            .addComponent(pbMainSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnReaderSearchLayout.setVerticalGroup(
            pnReaderSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnReaderSearchLayout.createSequentialGroup()
                .addComponent(pbMainSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnReaderSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbResInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbPrevious, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbNext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbCurrent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnReaderSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbResImg2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbResImg1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbResImg4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbResImg3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbResImg5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnReaderSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbResTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbResTxt4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbResTxt5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbResTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbResTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnReaderSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbResImg7, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbResImg6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbResImg9, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbResImg8, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbResImg10, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnReaderSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbResTxt7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbResTxt9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbResTxt10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbResTxt8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbResTxt6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );

        lbResImg7.getAccessibleContext().setAccessibleName("lbResImg7");
        lbResTxt2.getAccessibleContext().setAccessibleName("lbResTxt2");
        lbResImg6.getAccessibleContext().setAccessibleName("lbResImg6");
        lbResImg8.getAccessibleContext().setAccessibleName("lbResImg8");
        lbResImg9.getAccessibleContext().setAccessibleName("lbResImg9");
        lbResImg10.getAccessibleContext().setAccessibleName("lbResImg10");
        lbResTxt1.getAccessibleContext().setAccessibleName("lbResTxt1");
        lbResTxt4.getAccessibleContext().setAccessibleName("lbResTxt4");
        lbResTxt5.getAccessibleContext().setAccessibleName("lbResTxt5");
        lbResTxt3.getAccessibleContext().setAccessibleName("lbResTxt3");
        lbResTxt6.getAccessibleContext().setAccessibleName("lbResTxt6");
        lbResTxt7.getAccessibleContext().setAccessibleName("lbResTxt7");
        lbResTxt8.getAccessibleContext().setAccessibleName("lbResTxt8");
        lbResTxt9.getAccessibleContext().setAccessibleName("lbResTxt9");
        lbResTxt10.getAccessibleContext().setAccessibleName("lbResTxt10");
        lbResImg1.getAccessibleContext().setAccessibleName("lbResImg1");
        lbResImg1.getAccessibleContext().setAccessibleDescription("lbResImg1");
        lbResImg2.getAccessibleContext().setAccessibleName("lbResImg2");
        lbResImg3.getAccessibleContext().setAccessibleName("lbResImg3");
        lbResImg4.getAccessibleContext().setAccessibleName("lbResImg4");
        lbResImg5.getAccessibleContext().setAccessibleName("lbResImg5");

        pnMain.add(pnReaderSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 830, 580));
        pnReaderSearch.getAccessibleContext().setAccessibleName("pnSearch");

        pnReaderHistory.setPreferredSize(new java.awt.Dimension(820, 480));

        lbResImg11.setBackground(new java.awt.Color(100, 240, 150));

        lbResImg12.setBackground(new java.awt.Color(100, 240, 150));

        lbResImg13.setBackground(new java.awt.Color(100, 240, 150));

        lbResImg14.setBackground(new java.awt.Color(100, 240, 150));
        lbResImg14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lbResImg15.setBackground(new java.awt.Color(100, 240, 150));
        lbResImg15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        pnReaderHistoryInfo.setBackground(new java.awt.Color(255, 255, 255));

        lbHInfo1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbHInfo1.setText("Bạn đã mượn ... cuốn sách");

        lbHInfo3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbHInfo3.setText("Hiện đang có ... cuốn chưa trả");

        lbHInfo2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lbHInfo2.setForeground(new java.awt.Color(0, 0, 102));
        lbHInfo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbHInfo2.setText("Xem các sách đã mượn");
        lbHInfo2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbHInfo4.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lbHInfo4.setForeground(new java.awt.Color(0, 0, 102));
        lbHInfo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbHInfo4.setText("Xem các sách chưa trả");
        lbHInfo4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout pnReaderHistoryInfoLayout = new javax.swing.GroupLayout(pnReaderHistoryInfo);
        pnReaderHistoryInfo.setLayout(pnReaderHistoryInfoLayout);
        pnReaderHistoryInfoLayout.setHorizontalGroup(
            pnReaderHistoryInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnReaderHistoryInfoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(pnReaderHistoryInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbHInfo3, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(lbHInfo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnReaderHistoryInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbHInfo2, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(lbHInfo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnReaderHistoryInfoLayout.setVerticalGroup(
            pnReaderHistoryInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnReaderHistoryInfoLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(pnReaderHistoryInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbHInfo2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnReaderHistoryInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHInfo3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbHInfo4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout pnReaderHistoryLayout = new javax.swing.GroupLayout(pnReaderHistory);
        pnReaderHistory.setLayout(pnReaderHistoryLayout);
        pnReaderHistoryLayout.setHorizontalGroup(
            pnReaderHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnReaderHistoryLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnReaderHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbResImg11, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnReaderHistoryLayout.createSequentialGroup()
                        .addComponent(lbResTxt16, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(pnReaderHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbResTxt17, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbResImg13, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(pnReaderHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnReaderHistoryLayout.createSequentialGroup()
                                .addComponent(lbResImg14, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(lbResImg15, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnReaderHistoryLayout.createSequentialGroup()
                                .addComponent(lbResTxt18, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(lbResTxt19, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(pnReaderHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbResImg12, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbResTxt20, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)))
                .addGap(14, 14, 14))
            .addComponent(pnReaderHistoryInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnReaderHistoryLayout.setVerticalGroup(
            pnReaderHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnReaderHistoryLayout.createSequentialGroup()
                .addComponent(pnReaderHistoryInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addGroup(pnReaderHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbResImg11, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbResImg12, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbResImg14, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbResImg13, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbResImg15, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnReaderHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbResTxt17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbResTxt19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbResTxt20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbResTxt18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbResTxt16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );

        pnMain.add(pnReaderHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 830, 580));

        pnReaderInfo.setBackground(new java.awt.Color(255, 255, 255));
        pnReaderInfo.setPreferredSize(new java.awt.Dimension(820, 480));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel1.setText("Giới tính:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel3.setText("Tên đăng nhập:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel4.setText("Họ và tên:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel5.setText("Ngày sinh:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel6.setText("Địa chỉ:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel7.setText("CMND:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel8.setText("Số điện thoại:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel9.setText("Email:");

        jTextField3.setText("jTextField3");
        jTextField3.setEnabled(false);

        jTextField4.setText("jTextField3");
        jTextField4.setEnabled(false);

        jTextField5.setText("jTextField3");
        jTextField5.setEnabled(false);

        jTextField6.setText("jTextField3");
        jTextField6.setEnabled(false);

        jTextField7.setText("jTextField3");
        jTextField7.setEnabled(false);

        jTextField8.setText("jTextField3");
        jTextField8.setEnabled(false);

        jTextField9.setText("jTextField3");
        jTextField9.setEnabled(false);

        jTextField10.setText("jTextField3");
        jTextField10.setEnabled(false);

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Thông tin tài khoản");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Khách hàng: Văn Minh Hào");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(313, 313, 313))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(305, 305, 305)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(0, 204, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Đổi mật khẩu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 204, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("Cập nhật thông tin");

        pnAvatar.setBackground(new java.awt.Color(255, 255, 255));

        lbAvatar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbBrowser.setBackground(new java.awt.Color(255, 255, 255));
        lbBrowser.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbBrowser.setForeground(new java.awt.Color(102, 102, 102));
        lbBrowser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBrowser.setText("Browser ...");
        lbBrowser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout pnAvatarLayout = new javax.swing.GroupLayout(pnAvatar);
        pnAvatar.setLayout(pnAvatarLayout);
        pnAvatarLayout.setHorizontalGroup(
            pnAvatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAvatarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnAvatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAvatar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbBrowser, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnAvatarLayout.setVerticalGroup(
            pnAvatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAvatarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbBrowser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnReaderInfoLayout = new javax.swing.GroupLayout(pnReaderInfo);
        pnReaderInfo.setLayout(pnReaderInfoLayout);
        pnReaderInfoLayout.setHorizontalGroup(
            pnReaderInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnReaderInfoLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(pnAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addGroup(pnReaderInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnReaderInfoLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField9))
                    .addGroup(pnReaderInfoLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField8))
                    .addGroup(pnReaderInfoLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField7))
                    .addGroup(pnReaderInfoLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField6))
                    .addGroup(pnReaderInfoLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField5))
                    .addGroup(pnReaderInfoLayout.createSequentialGroup()
                        .addGroup(pnReaderInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnReaderInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnReaderInfoLayout.createSequentialGroup()
                        .addGroup(pnReaderInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnReaderInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField10)
                            .addGroup(pnReaderInfoLayout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(258, 258, 258))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnReaderInfoLayout.setVerticalGroup(
            pnReaderInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnReaderInfoLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnReaderInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnReaderInfoLayout.createSequentialGroup()
                        .addGroup(pnReaderInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField3)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnReaderInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnReaderInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnReaderInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6)))
                    .addGroup(pnReaderInfoLayout.createSequentialGroup()
                        .addComponent(pnAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnReaderInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnReaderInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnReaderInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnReaderInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10))
                .addGap(47, 47, 47)
                .addGroup(pnReaderInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(104, 104, 104))
        );

        pnMain.add(pnReaderInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 830, 580));

        getContentPane().add(pnMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1010, 540));

        jPanel4.setBackground(new java.awt.Color(53, 53, 53));
        jPanel4.setPreferredSize(new java.awt.Dimension(1000, 43));

        lbCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/Cancel_32px.png"))); // NOI18N
        lbCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbCancelMouseClicked(evt);
            }
        });

        lbMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/Minimize Window_32px_2.png"))); // NOI18N
        lbMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMinimizeMouseClicked(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Thư Viện Đại Học Bách Khoa");

        lbMinimize1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/bkLogo3.png"))); // NOI18N
        lbMinimize1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbMinimize1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 334, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(304, 304, 304)
                .addComponent(lbMinimize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbCancel)
                .addGap(21, 21, 21))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(lbMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbMinimize1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 30));

        jPanel1.setBackground(new java.awt.Color(40, 171, 227));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1010, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCancelMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lbCancelMouseClicked

    private void lbMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMinimizeMouseClicked
        // TODO add your handling code here:
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_lbMinimizeMouseClicked

    private void lbSearch1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSearch1MouseExited
        // TODO add your handling code here:
        pnSearch.setBackground(new Color(38,40,55));
    }//GEN-LAST:event_lbSearch1MouseExited

    private void lbSearch1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSearch1MouseEntered
        // TODO add your handling code here:
        pnSearch.setBackground(new Color(0, 116, 163));
    }//GEN-LAST:event_lbSearch1MouseEntered

    private void lbUserInfor1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbUserInfor1MouseExited
        // TODO add your handling code here:
        pnUser.setBackground(new Color(38,40,55));
    }//GEN-LAST:event_lbUserInfor1MouseExited

    private void lbUserInfor1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbUserInfor1MouseEntered
        // TODO add your handling code here:
        pnUser.setBackground(new Color(0, 116, 163));
    }//GEN-LAST:event_lbUserInfor1MouseEntered

    private void lbHistory1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbHistory1MouseExited
        // TODO add your handling code here:
        pnHistory.setBackground(new Color(38,40,55));
    }//GEN-LAST:event_lbHistory1MouseExited

    private void lbHistory1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbHistory1MouseEntered
        // TODO add your handling code here:
        pnHistory.setBackground(new Color(0, 116, 163));
    }//GEN-LAST:event_lbHistory1MouseEntered

    private void lbHome1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbHome1MouseExited
        // TODO add your handling code here:
        pnHome.setBackground(new Color(38,40,55));
    }//GEN-LAST:event_lbHome1MouseExited

    private void lbHome1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbHome1MouseEntered
        // TODO add your handling code here:
        pnHome.setBackground(new Color(0, 116, 163));
    }//GEN-LAST:event_lbHome1MouseEntered

    private void tfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSearchActionPerformed
        // TODO add your handling code here:
        res = DatabaseQuery.SearchBookByKeyWord(tfSearch.getText());
        resultNum = SupportFunctions.GetSize(res);
        lbResInfo.setText("Có tất cả " + String.valueOf(resultNum) + " kết quả:");
    }//GEN-LAST:event_tfSearchActionPerformed

    private void lbSearch1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSearch1MouseClicked
        // TODO add your handling code here:
        changeBackPanel(1);
    }//GEN-LAST:event_lbSearch1MouseClicked

    private void lbHistory1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbHistory1MouseClicked
        // TODO add your handling code here:
        changeBackPanel(2);
    }//GEN-LAST:event_lbHistory1MouseClicked

    private void cbNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNameActionPerformed

    private void cbNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbNameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNameMouseClicked

    private void cbAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAuthorActionPerformed

    private void cbAuthorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbAuthorMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAuthorMouseClicked

    private void cbGenreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbGenreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGenreMouseClicked

    private void cbPublisherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbPublisherMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPublisherMouseClicked

    private void cbIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbIDMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbIDMouseClicked

    private void cbISBNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbISBNMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbISBNMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lbUserInfor1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbUserInfor1MouseClicked
        // TODO add your handling code here:
        changeBackPanel(3);
    }//GEN-LAST:event_lbUserInfor1MouseClicked

    private void lbHome1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbHome1MouseClicked
        // TODO add your handling code here:
        dispose();
        new HomePage().setVisible(true);
    }//GEN-LAST:event_lbHome1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReaderMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReaderMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReaderMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReaderMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReaderMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbAuthor;
    private javax.swing.JCheckBox cbGenre;
    private javax.swing.JCheckBox cbID;
    private javax.swing.JCheckBox cbISBN;
    private javax.swing.JCheckBox cbName;
    private javax.swing.JCheckBox cbPublisher;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lbAvatar;
    private javax.swing.JLabel lbBrowser;
    private javax.swing.JLabel lbCancel;
    private javax.swing.JLabel lbCurrent;
    private javax.swing.JLabel lbHInfo1;
    private javax.swing.JLabel lbHInfo2;
    private javax.swing.JLabel lbHInfo3;
    private javax.swing.JLabel lbHInfo4;
    private javax.swing.JLabel lbHistory;
    private javax.swing.JLabel lbHistory1;
    private javax.swing.JLabel lbHome;
    private javax.swing.JLabel lbHome1;
    private javax.swing.JLabel lbMinimize;
    private javax.swing.JLabel lbMinimize1;
    private javax.swing.JLabel lbNext;
    private javax.swing.JLabel lbPrevious;
    private javax.swing.JLabel lbResImg1;
    private javax.swing.JLabel lbResImg10;
    private javax.swing.JLabel lbResImg11;
    private javax.swing.JLabel lbResImg12;
    private javax.swing.JLabel lbResImg13;
    private javax.swing.JLabel lbResImg14;
    private javax.swing.JLabel lbResImg15;
    private javax.swing.JLabel lbResImg2;
    private javax.swing.JLabel lbResImg3;
    private javax.swing.JLabel lbResImg4;
    private javax.swing.JLabel lbResImg5;
    private javax.swing.JLabel lbResImg6;
    private javax.swing.JLabel lbResImg7;
    private javax.swing.JLabel lbResImg8;
    private javax.swing.JLabel lbResImg9;
    private javax.swing.JLabel lbResInfo;
    private javax.swing.JLabel lbResTxt1;
    private javax.swing.JLabel lbResTxt10;
    private javax.swing.JLabel lbResTxt16;
    private javax.swing.JLabel lbResTxt17;
    private javax.swing.JLabel lbResTxt18;
    private javax.swing.JLabel lbResTxt19;
    private javax.swing.JLabel lbResTxt2;
    private javax.swing.JLabel lbResTxt20;
    private javax.swing.JLabel lbResTxt3;
    private javax.swing.JLabel lbResTxt4;
    private javax.swing.JLabel lbResTxt5;
    private javax.swing.JLabel lbResTxt6;
    private javax.swing.JLabel lbResTxt7;
    private javax.swing.JLabel lbResTxt8;
    private javax.swing.JLabel lbResTxt9;
    private javax.swing.JLabel lbSearch;
    private javax.swing.JLabel lbSearch1;
    private javax.swing.JLabel lbSearch100;
    private javax.swing.JLabel lbUserInfor;
    private javax.swing.JLabel lbUserInfor1;
    private javax.swing.JPanel pbMainSearch;
    private javax.swing.JPanel pnAvatar;
    private javax.swing.JPanel pnHistory;
    private javax.swing.JPanel pnHome;
    private javax.swing.JPanel pnLeft;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnReaderHistory;
    private javax.swing.JPanel pnReaderHistoryInfo;
    private javax.swing.JPanel pnReaderInfo;
    private javax.swing.JPanel pnReaderSearch;
    private javax.swing.JPanel pnSearch;
    private javax.swing.JPanel pnUser;
    private javax.swing.JTextField tfSearch;
    // End of variables declaration//GEN-END:variables
}
