/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.geom.RoundRectangle2D;
import javax.swing.JOptionPane;
import main.DatabaseQuery;
import main.People;

/**
 *
 * @author Thành
 */
public class ScanID extends javax.swing.JFrame {

    /**
     * Creates new form ScanID
     */
    public ScanID() {
        initComponents();
        this.setShape(new RoundRectangle2D.Float(0, 0, 300, 300, 45, 45));
        this.setSize(300, 300);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        tfID = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(38, 40, 55));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(45, 59, 85));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCancel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(0, 0, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 245, -1, -1));

        tfID.setBackground(new java.awt.Color(45, 59, 85));
        tfID.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        tfID.setForeground(new java.awt.Color(255, 255, 255));
        tfID.setBorder(null);
        tfID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfIDFocusLost(evt);
            }
        });
        jPanel1.add(tfID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 200, 39));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 200, 17));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quét mã vạch");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 200, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        one.stop();
        this.dispose();
        new LoginSite().show();
                
    }//GEN-LAST:event_btnCancelActionPerformed

    private void tfIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfIDFocusGained
        // TODO add your handling code here:
       one.start();
    }//GEN-LAST:event_tfIDFocusGained

    private void tfIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfIDFocusLost
        // TODO add your handling code here:
       
    }//GEN-LAST:event_tfIDFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScanID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScanID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScanID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScanID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScanID().setVisible(true);
            }
        });
    }

    Thread one = new Thread() {
        public void run() {
            String text;
            while (true) {
                text = tfID.getText();
                System.out.println(text);
                if (text.length() == 7) {
                    tfID.requestFocus(false);
                    People user = DatabaseQuery.findUserByID(text, "admin");
                    if (user != null) {
                        dispose();
                        new Admin(user).show();
                        JOptionPane.showMessageDialog(null, "Đăng nhập thành công! Xin chào "+ user.getFullName() +". Đăng nhập với tư cách Admin");
                        stop();
                        break;
                    } else {
                        user = DatabaseQuery.findUserByID(text, "doc_gia");
                        if (user != null) {
                            dispose();
                            new ReaderMain(user).show();
                            JOptionPane.showMessageDialog(null, "Đăng nhập thành công! Xin chào "+ user.getFullName()+". Đăng nhập với tư cách Độc giả");
                            stop();
                            break;
                        } else {
                            user = DatabaseQuery.findUserByID(text, "nguoi_quan_ly");
                            if (user != null) {
                                dispose();
                                new Management(user).show();
                                JOptionPane.showMessageDialog(null, "Đăng nhập thành công! Xin chào "+ user.getFullName()+". Đăng nhập với tư cách Thủ thư");
                                tfID.setText("");
                                stop();
                                break;
                            }
                            else
                            {
                                tfID.setText("");
                                hide();
                                JOptionPane.showMessageDialog(getOwner(), "ID không tồn tại, vui lòng kiểm tra lại", "Lỗi", JOptionPane.ERROR_MESSAGE);
                                show();
                            }
                        }
                    }
                }
            }
        }
    };

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField tfID;
    // End of variables declaration//GEN-END:variables
}
